// ─────────────────────────────────────────────────────────────────────────────
// LogicFlow.Guardian — Smart Driver Updater: Scan Result Models
// Rich result types with AI risk scoring for the 3-tier driver architecture.
// ─────────────────────────────────────────────────────────────────────────────

namespace LogicFlow.Guardian;

/// <summary>
/// Complete driver scan result aggregating all 3 tiers:
///   Tier 1 — Windows Update (pnputil)
///   Tier 2 — Curated Firestore driver index
///   Tier 3 — AI crash-to-driver correlation (Vertex AI / Gemini)
/// </summary>
public sealed class DriverScanResult
{
    /// <summary> Tier 1: Drivers available via Windows Update / pnputil. </summary>
    public List<DriverUpdateInfo> WindowsUpdateAvailable { get; init; } = new();

    /// <summary> Tier 2: Drivers available from the curated Firestore index (OEM download URLs). </summary>
    public List<DriverUpdateInfo> IndexAvailable { get; init; } = new();

    /// <summary> Tier 3: AI-powered recommendations based on crash correlation. </summary>
    public List<AiDriverRecommendation> AiRecommendations { get; init; } = new();

    /// <summary> All installed devices with current driver info. </summary>
    public List<DriverReport> InstalledDevices { get; init; } = new();

    /// <summary> BIOS/UEFI firmware information. </summary>
    public FirmwareInfo? Firmware { get; init; }

    /// <summary> When the scan was performed. </summary>
    public DateTimeOffset ScannedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary> Returns total available updates across all 3 tiers (de-duped by hardware ID). </summary>
    public int TotalUpdatesAvailable =>
        WindowsUpdateAvailable
            .Concat(IndexAvailable)
            .Select(u => u.HardwareId)
            .Distinct()
            .Count();
}

/// <summary>
/// AI-powered driver recommendation based on crash telemetry correlation.
/// Generated by Vertex AI / Gemini analyzing Pulse health digests.
/// </summary>
public sealed class AiDriverRecommendation
{
    /// <summary> The driver/device name (e.g., "NVIDIA GeForce GTX 4070"). </summary>
    public string DriverName { get; init; } = "";

    /// <summary> Hardware ID pattern this applies to. </summary>
    public string HardwareId { get; init; } = "";

    /// <summary>
    /// Human-readable reason for the recommendation.
    /// e.g., "3 BSODs this week linked to nvlddmkm.sys — update to v560.94 recommended."
    /// </summary>
    public string Reason { get; init; } = "";

    /// <summary> AI confidence score (0.0 – 1.0). </summary>
    public double Confidence { get; init; }

    /// <summary> Severity: "critical", "recommended", or "optional". </summary>
    public string Severity { get; init; } = "optional";

    /// <summary> Crash signatures that triggered this recommendation. </summary>
    public List<string> CrashSignatures { get; init; } = new();

    /// <summary> Number of crashes correlated to this driver in the time window. </summary>
    public int CrashCount { get; init; }

    /// <summary> The suggested update to install (from Tier 2 index), if available. </summary>
    public DriverUpdateInfo? SuggestedUpdate { get; init; }
}

/// <summary>
/// System BIOS / UEFI firmware information from WMI Win32_BIOS.
/// </summary>
public sealed class FirmwareInfo
{
    /// <summary> BIOS manufacturer (e.g., "American Megatrends Inc."). </summary>
    public string Manufacturer { get; init; } = "";

    /// <summary> BIOS version string (e.g., "F15"). </summary>
    public string Version { get; init; } = "";

    /// <summary> Full SMBIOS version (e.g., "3.4"). </summary>
    public string SmbiosVersion { get; init; } = "";

    /// <summary> BIOS release date. </summary>
    public DateTimeOffset? ReleaseDate { get; init; }

    /// <summary> Serial number (anonymized — last 4 chars only for support). </summary>
    public string SerialNumberSuffix { get; init; } = "";

    /// <summary> Whether UEFI Capsule firmware updates are likely supported. </summary>
    public bool UefiCapsuleSupported { get; init; }

    /// <summary> System model from Win32_ComputerSystem. </summary>
    public string SystemModel { get; init; } = "";

    /// <summary> System manufacturer. </summary>
    public string SystemManufacturer { get; init; } = "";
}

/// <summary>
/// Extension methods for the existing DriverReport record (defined in GuardianEngine.cs).
/// Adds category mapping for the driver scan UI grouping.
/// </summary>
public static class DriverReportExtensions
{
    /// <summary> Maps DeviceClass to UI display category (GPU, Audio, Network, etc.). </summary>
    public static string GetCategory(this DriverReport report) => report.DeviceClass switch
    {
        "Display" or "Display adapters" => "GPU",
        "MEDIA" or "Sound, video and game controllers" or
            "AudioEndpoint" => "Audio",
        "Net" or "Network adapters" => "Network",
        "DiskDrive" or "Disk drives" or
            "SCSIAdapter" or "Storage controllers" or
            "hdc" or "IDE ATA/ATAPI controllers" => "Storage",
        "USB" or "Universal Serial Bus controllers" => "USB",
        "Bluetooth" => "Bluetooth",
        "HIDClass" or "Human Interface Devices" or
            "Mouse" or "Keyboards" => "Input",
        "Image" or "Cameras" or "Camera" => "Camera",
        "Monitor" or "Monitors" => "Monitor",
        "Processor" or "Processors" => "Chipset",
        "System" or "System devices" => "System",
        "Firmware" => "Firmware",
        _ => "Other"
    };
}

/// <summary>
/// Known crash-to-driver correlation mappings.
/// Used locally for instant matching before AI analysis.
/// </summary>
public static class KnownDriverCrashPatterns
{
    /// <summary>
    /// Maps crash module names to likely device categories.
    /// Used to flag drivers as potentially crash-causing without waiting for AI.
    /// </summary>
    public static readonly Dictionary<string, DriverCrashPattern> Patterns = new(StringComparer.OrdinalIgnoreCase)
    {
        ["nvlddmkm.sys"] = new("NVIDIA GPU", "GPU",
            "VIDEO_TDR_FAILURE with nvlddmkm.sys — NVIDIA graphics driver crash"),
        ["nvlddmkm"] = new("NVIDIA GPU", "GPU",
            "NVIDIA kernel-mode driver crash detected"),
        ["atikmdag.sys"] = new("AMD GPU", "GPU",
            "AMD Radeon graphics driver crash (atikmdag.sys)"),
        ["atikmpag.sys"] = new("AMD GPU", "GPU",
            "AMD Radeon kernel-mode driver crash (atikmpag.sys)"),
        ["igdkmd64.sys"] = new("Intel GPU", "GPU",
            "Intel Graphics kernel-mode driver crash"),
        ["igdkmd32.sys"] = new("Intel GPU", "GPU",
            "Intel Graphics kernel-mode driver crash (32-bit)"),
        ["dxgkrnl.sys"] = new("Graphics Subsystem", "GPU",
            "DirectX graphics kernel crash — likely GPU driver issue"),
        ["dxgmms1.sys"] = new("Graphics Subsystem", "GPU",
            "DirectX memory management crash — GPU driver instability"),
        ["Realtek"] = new("Realtek Audio", "Audio",
            "Realtek audio driver event error detected"),
        ["RTKVHD64.sys"] = new("Realtek Audio", "Audio",
            "Realtek HD Audio driver crash"),
        ["portcls.sys"] = new("Audio Subsystem", "Audio",
            "Windows audio port class driver crash — likely audio driver issue"),
        ["e1d65x64.sys"] = new("Intel Ethernet", "Network",
            "Intel Ethernet adapter driver crash"),
        ["rt640x64.sys"] = new("Realtek Ethernet", "Network",
            "Realtek network adapter driver crash"),
        ["mwlu97w8x64.sys"] = new("MediaTek WiFi", "Network",
            "MediaTek wireless adapter driver crash"),
        ["Netwtw10.sys"] = new("Intel WiFi", "Network",
            "Intel WiFi adapter driver crash"),
        ["NETwNe64.sys"] = new("Intel WiFi", "Network",
            "Intel wireless adapter driver crash"),
        ["bthhfenum.sys"] = new("Bluetooth", "Bluetooth",
            "Bluetooth HFP driver crash"),
        ["bthmodem.sys"] = new("Bluetooth", "Bluetooth",
            "Bluetooth modem driver crash"),
        ["NTFS.sys"] = new("Storage", "Storage",
            "NTFS file system crash — possible storage controller driver issue"),
        ["storport.sys"] = new("Storage Controller", "Storage",
            "Storage port driver crash — storage controller instability"),
        ["stornvme.sys"] = new("NVMe Controller", "Storage",
            "NVMe storage driver crash"),
        ["iaStorAC.sys"] = new("Intel RST", "Storage",
            "Intel Rapid Storage Technology driver crash"),
        ["USBXHCI.sys"] = new("USB Controller", "USB",
            "USB xHCI host controller driver crash"),
        ["ucx01000.sys"] = new("USB Controller", "USB",
            "USB controller extension driver crash"),
    };
}

/// <summary>
/// A known crash-to-driver pattern used for local matching.
/// </summary>
public sealed record DriverCrashPattern(
    string DriverName,
    string DeviceCategory,
    string Description);
